### ISSUE TITLE
Notes on further rxinu scheduling changes

### ISSUE THREAD

**Issue by robert-w-gries** [too-r/lambdaOS#5]
I finally merged my scheduling code into `rxinu`'s master branch and wanted to leave some notes regarding my final changes and thoughts on some experimental portions of my scheduler.  I hope my code has been working for you so far!

### Bug: Freeing the allocated kernel stack

This issue was the culprit of some strange errors I have seen while testing the scheduler.  Simply setting the `kstack` to `None` does not deallocate the processes's kernel stack.  I discovered this issue while testing a process creation cycle where `ProcessA` calls `create(ProcessB)` and `ProcessB` calls `create(ProcessA)`.  While running this test, I would hit strange behavior that resulted in page faults and double faults because the incorrect `kstack` pointer would be freed or memory wasn't actually allocated.

[The issue was fixed by calling `drop` on `&mut kstack`](https://github.com/robert-w-gries/rxinu/commit/30d33dbbe5ba4fd7abe9771e227133591d16e2ea#diff-661291fc8db365d315a964bd9bdb03f2R80)

### Experimental dynamic dispatch

I went back and forth on whether I should include [the experimental scheduler dynamic dispatch in the process return](https://github.com/robert-w-gries/rxinu/commit/30d33dbbe5ba4fd7abe9771e227133591d16e2ea#diff-90bec723033c4179002a65c12b0b429bR102).  I ultimately decided to keep it in since it works and it can be easily removed if it's determined unnecessary.  Since this aspect of the scheduler is not thoroughly discussed in my code, I'll leave some notes here.

To provide context, I initially avoided a global scheduling object because I generally view singletons as a last resort.  Though I eventually decided that the singleton pattern fit our use case, the majority of my scheduler code was written with the mindset that an arbitrary number of schedulers could be created and used to schedule processes independently of each other.

One of the challenges I faced with this design choice was killing the process in its `process_return` function.  The `self` reference to the scheduler object is lost after context switching to a new process in `resched()`.  So when we jump from the new process to `process_ret()`, we have no access to the original scheduler object and therefore could not call `self.kill()` or manipulate the proper scheduler's `ProcessList`.  My solution was to push a pointer to the scheduler object onto the kernel stack, pop the pointer off the kernel stack in `process_ret()`, and convert the pointer into a [trait object](https://doc.rust-lang.org/book/first-edition/trait-objects.html).  Dynamic dispatch is then used to call the `getid()` and `kill()` methods.

One limitation of my initial solution is that it assumes the scheduler object is a `CoopScheduler`.  I have fixed that in [this commit](https://github.com/robert-w-gries/rxinu/commit/d3d76778c2f4ea449423f707c69156b9eb5e235e).  Now, the `kill()` method is agnostic of scheduler type.

**Comment by too-r** [comment]
I appreciate the work you've done, and thank your for these insights on the design of your scheduling code. I was having difficulty coming up with a good scheduler model - your code helped me with that, so thanks. I saw in #33 that you were wanting to build a PIT driver, is this something I could help with?

**Comment by robert-w-gries** [comment]
Glad to hear it!

> I saw in #33 that you were wanting to build a PIT driver, is this something I could help with?

That'd be great!  The PIT driver is pretty important for my kernel as I am planning on implementing preemption and a priority scheduler.

I have several tasks in mind (documentation, testing framework, proper memory management setup) before taking on preemption, so any help with the PIT driver will be greatly appreciated 😄

**Comment by too-r** [comment]
Sounds great, I'll get to work on it then.
